// xCoin tetromino identicon V1 — faithful port of xcoin_identicon.py
const N=12,COL={I:'#ff1400',O:'#ff8a00',T:'#fff200',L:'#00e834',J:'#113cff',S:'#a61fff',Z:'#42107a'};
const SHAPES={I:[[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[0,2],[0,3]]],O:[[[0,0],[1,0],[0,1],[1,1]]],T:[[[0,0],[1,0],[2,0],[1,1]],[[0,0],[0,1],[0,2],[1,1]],[[1,0],[0,1],[1,1],[2,1]],[[1,0],[0,1],[1,1],[1,2]]],L:[[[0,0],[0,1],[0,2],[1,2]],[[0,0],[1,0],[2,0],[0,1]],[[0,0],[1,0],[1,1],[1,2]],[[2,0],[0,1],[1,1],[2,1]]],J:[[[1,0],[1,1],[0,2],[1,2]],[[0,0],[0,1],[1,1],[2,1]],[[0,0],[1,0],[0,1],[0,2]],[[0,0],[1,0],[2,0],[2,1]]],S:[[[1,0],[2,0],[0,1],[1,1]],[[0,0],[0,1],[1,1],[1,2]]],Z:[[[0,0],[1,0],[1,1],[2,1]],[[1,0],[0,1],[1,1],[0,2]]]};
// compact sync sha256
const K=[];for(let i=0,n=2;i<64;n++){let p=true;for(let j=2;j*j<=n;j++)if(n%j==0){p=false;break}if(p){K[i++]=(Math.cbrt(n)%1*4294967296)|0}}
const H0=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19];
function sha256(msg){const l=msg.length,bl=l*8,pad=((l+9+63)>>6)<<6,b=new Uint8Array(pad);b.set(msg);b[l]=0x80;const dv=new DataView(b.buffer);dv.setUint32(pad-4,bl>>>0);dv.setUint32(pad-8,Math.floor(bl/4294967296));const h=H0.slice(),w=new Int32Array(64);for(let o=0;o<pad;o+=64){for(let i=0;i<16;i++)w[i]=dv.getInt32(o+i*4);for(let i=16;i<64;i++){const a=w[i-15],c=w[i-2];w[i]=(w[i-16]+(((a>>>7)|(a<<25))^((a>>>18)|(a<<14))^(a>>>3))+w[i-7]+(((c>>>17)|(c<<15))^((c>>>19)|(c<<13))^(c>>>10)))|0}let[a,b2,c,d,e,f,g,hh]=h;for(let i=0;i<64;i++){const t1=(hh+(((e>>>6)|(e<<26))^((e>>>11)|(e<<21))^((e>>>25)|(e<<7)))+((e&f)^(~e&g))+K[i]+w[i])|0,t2=((((a>>>2)|(a<<30))^((a>>>13)|(a<<19))^((a>>>22)|(a<<10)))+((a&b2)^(a&c)^(b2&c)))|0;hh=g;g=f;f=e;e=(d+t1)|0;d=c;c=b2;b2=a;a=(t1+t2)|0}h[0]=(h[0]+a)|0;h[1]=(h[1]+b2)|0;h[2]=(h[2]+c)|0;h[3]=(h[3]+d)|0;h[4]=(h[4]+e)|0;h[5]=(h[5]+f)|0;h[6]=(h[6]+g)|0;h[7]=(h[7]+hh)|0}const out=new Uint8Array(32),ov=new DataView(out.buffer);h.forEach((v,i)=>ov.setUint32(i*4,v>>>0));return out}
const enc=s=>new TextEncoder().encode(s),cat=(...a)=>{const r=new Uint8Array(a.reduce((s,x)=>s+x.length,0));let o=0;for(const x of a){r.set(x,o);o+=x.length}return r},hex=u=>[...u].map(b=>b.toString(16).padStart(2,'0')).join('');
// bech32m
const B32="qpzry9x8gf2tvdw0s3jn54khce6mua7l";
function polymod(v){const g=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3];let c=1;for(const x of v){const t=c>>>25;c=((c&0x1ffffff)<<5)^x;for(let i=0;i<5;i++)if((t>>i)&1)c^=g[i]}return c>>>0}
function decode(addr){addr=addr.trim().toLowerCase();const p=addr.lastIndexOf('1');if(p<1)throw Error('malformed address');const hrp=addr.slice(0,p),rest=addr.slice(p+1);const data=[...rest].map(ch=>{const i=B32.indexOf(ch);if(i<0)throw Error('bad char');return i});const ex=[...hrp].map(ch=>ch.charCodeAt(0)>>5).concat([0],[...hrp].map(ch=>ch.charCodeAt(0)&31));if(polymod(ex.concat(data))!==0x2bc830a3)throw Error('bad bech32m checksum');const d=data.slice(0,-6),wv=d[0];let acc=0,bits=0;const out=[];for(const v of d.slice(1)){acc=((acc<<5)|v)&0xfff;bits+=5;while(bits>=8){bits-=8;out.push((acc>>bits)&255)}}if(bits>=5||((acc<<(8-bits))&255))throw Error('bad padding');return{hrp,wv,prog:new Uint8Array(out)}}
function seedOf(addr){const{hrp,wv,prog}=decode(addr);if(wv!==3||prog.length!==32)throw Error('expected witness-v3 xCoin address with 32-byte program');return{hrp,wv,prog,seed:sha256(cat(enc("XCOIN_IDENTICON_V1"),enc(hrp),new Uint8Array([wv]),prog))}}
// placements (built once)
let PL,C2P,ADJ;
function build(){PL=[];C2P=Array.from({length:N*N},()=>[]);ADJ=Array.from({length:N*N},(_,c)=>{const x=c%N,y=c/N|0,r=[];for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy;if(nx>=0&&nx<N&&ny>=0&&ny<N)r.push(ny*N+nx)}return r});
for(const[fam,ors]of Object.entries(SHAPES))ors.forEach((pts,ori)=>{const mx=Math.max(...pts.map(p=>p[0])),my=Math.max(...pts.map(p=>p[1]));for(let oy=0;oy<N-my;oy++)for(let ox=0;ox<N-mx;ox++){const cells=pts.map(([x,y])=>(oy+y)*N+ox+x).sort((a,b)=>a-b);const idx=PL.length;const p={family:fam,orientation:ori,cells,anchor:[ox,oy],key:enc(`${fam}|${ori}|${cells.join(',')}`)};PL.push(p);cells.forEach(c=>C2P[c].push(idx))}});
for(const p of PL){const s=new Set(p.cells),nb=new Set();for(const c of p.cells)for(const nc of ADJ[c])if(!s.has(nc))nb.add(nc);p.nb=[...nb]}}
export function layout(addr){if(!PL)build();const{hrp,wv,prog,seed}=seedOf(addr);const occ=new Int16Array(N*N).fill(-1),placed=[];
const legal=pi=>{const p=PL[pi];for(const c of p.cells)if(occ[c]!==-1)return false;for(const nc of p.nb){const o=occ[nc];if(o!==-1&&placed[o].family===p.family)return false}return true};
const holesOk=()=>{const seen=new Uint8Array(N*N);for(let c=0;c<N*N;c++)if(occ[c]===-1&&!seen[c]){const st=[c];seen[c]=1;let sz=0;while(st.length){const u=st.pop();sz++;for(const v of ADJ[u])if(occ[v]===-1&&!seen[v]){seen[v]=1;st.push(v)}}if(sz%4)return false}return true};
const choose=()=>{let best=null;for(let c=0;c<N*N;c++){if(occ[c]!==-1)continue;const cands=C2P[c].filter(legal);if(!cands.length)return[];if(!best||cands.length<best.length){best=cands;if(best.length===1)break}}return best};
const order=(step,cands)=>{const sb=new Uint8Array([step&255,step>>8]);return cands.map(pi=>[hex(sha256(cat(seed,sb,PL[pi].key))),pi]).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0).map(x=>x[1])};
const solve=step=>{if(step===N*N/4)return true;const cands=choose();if(!cands.length)return false;for(const pi of order(step,cands)){const p=PL[pi],id=placed.length;for(const c of p.cells)occ[c]=id;placed.push(p);if(holesOk()&&solve(step+1))return true;placed.pop();for(const c of p.cells)occ[c]=-1}return false};
if(!solve(0))throw Error('No valid layout found');
return{address:addr,hrp,witver:wv,program_hex:hex(prog),seed_hex:hex(seed),pieces:placed.map(p=>({family:p.family,orientation:p.orientation,cells:p.cells,anchor:p.anchor})),board_owner:[...occ]}}
export function svg(l,cell=64){const W=N*cell;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${W}" viewBox="0 0 ${W} ${W}" shape-rendering="crispEdges">`;for(let y=0;y<N;y++)for(let x=0;x<N;x++)s+=`<rect x="${x*cell}" y="${y*cell}" width="${cell}" height="${cell}" fill="${COL[l.pieces[l.board_owner[y*N+x]].family]}"/>`;return s+'</svg>'}
const HTML=`<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>xCoin Identicon</title>
<style>body{font-family:system-ui;background:#0b0b0f;color:#eee;margin:0;padding:24px;display:flex;flex-direction:column;align-items:center;gap:16px}input{width:min(600px,90vw);padding:10px;font-size:14px;border-radius:8px;border:1px solid #333;background:#16161d;color:#eee}#o svg{width:min(384px,80vw);height:auto;border-radius:12px}code{color:#9aa}</style>
<h1>xCoin Tetromino Identicon</h1><input id=a placeholder="xpa1r… / txa1r… address" autofocus><div id=o></div><p id=e style="color:#f66"></p>
<p><code>GET /api/svg?a=ADDRESS</code> · <code>GET /api/json?a=ADDRESS</code></p>
<script>const a=document.getElementById('a'),o=document.getElementById('o'),e=document.getElementById('e');let t;a.oninput=()=>{clearTimeout(t);t=setTimeout(async()=>{const v=a.value.trim();if(!v)return;const r=await fetch('/api/svg?a='+encodeURIComponent(v));if(r.ok){o.innerHTML=await r.text();e.textContent=''}else{o.innerHTML='';e.textContent=await r.text()}},250)};const q=new URLSearchParams(location.search).get('a');if(q){a.value=q;a.oninput()}</script>`;
export default{async fetch(req){const u=new URL(req.url),a=u.searchParams.get('a')||'';const cors={'access-control-allow-origin':'*'};try{
if(u.pathname==='/api/svg')return new Response(svg(layout(a),+u.searchParams.get('cell')||64),{headers:{...cors,'content-type':'image/svg+xml','cache-control':'public,max-age=31536000,immutable'}});
if(u.pathname==='/api/json')return new Response(JSON.stringify(layout(a)),{headers:{...cors,'content-type':'application/json','cache-control':'public,max-age=31536000,immutable'}});
}catch(err){return new Response(err.message,{status:400,headers:cors})}
return new Response(HTML,{headers:{'content-type':'text/html;charset=utf-8'}})}}
